### PR TITLE
Picking different proxy types.

### PR DESCRIPTION
**Pull request by medse**
That's a beginning, now it's possible to pass ua type to fake-user-agent. #6

### CODE REVIEW

**Comment by lockie** [comment]
Hey do you mind bumping package version on pypi so that this great improvement gets there?

**Comment by alecxe** [comment]
@lockie oops, I thought I did that, my bad. Will do, thanks for pinging me here.

**Comment by lockie** [comment]
No problem, thanks :)

**Comment by alecxe** [comment]
@lockie should be there on PyPI. Forgot all the sorry state (or that's just me not getting something) of packaging with PyPI, had to do it manually.. Please check.

**Comment by lockie** [comment]
@alecxe Thanks, it works!

The only strange thing though is that `pip freeze` reports package version as 1.0.4 even though it actually is 1.0.4.1, but that's pip's glitch I guess.

**Comment by alecxe** [comment]
@lockie right, that's because PyPI does not allow to reupload a package file with the same name, even if it happened accidentally or for a completely different package version, weird validation requirements which I had to workaround with the ".1" prefix. Sorry, thanks for noticing that.

**Comment by lockie** [comment]
@alecxe Oh I see. No problem :)

**Pull request merged**
